// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalOrganizer.Domain.DataAccess;

namespace PersonalOrganizer.Domain.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PersonalOrganizer.Domain.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoteText")
                        .HasColumnType("text");

                    b.HasKey("NoteId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PersonalOrganizer.Domain.Models.ToDo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreated = new DateTime(2021, 3, 6, 14, 47, 25, 536, DateTimeKind.Local).AddTicks(2600),
                            Description = "Feed the dog",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2L,
                            DateCreated = new DateTime(2021, 3, 6, 14, 47, 25, 552, DateTimeKind.Local).AddTicks(50),
                            Description = "Feed the cat",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3L,
                            DateCreated = new DateTime(2021, 3, 6, 14, 47, 25, 552, DateTimeKind.Local).AddTicks(70),
                            Description = "Walk the dog",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 4L,
                            DateCreated = new DateTime(2021, 3, 6, 14, 47, 25, 552, DateTimeKind.Local).AddTicks(70),
                            Description = "Change cat litter",
                            IsCompleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
